version: 2.1

vars:
  branch_master: &branch_master
    filters:
      branches:
        only: master

  branch_testing: &branch_testing
    filters:
      branches:
        ignore:
          - /^prod\//
          - master

executors:
  node:
    environment:
      - TZ: Asia/Taipei
    docker:
      - image: circleci/node:12

commands:
    setup-npm:
      parameters:
        token:
          type: string
          default: $NPM_TOKEN
      steps:
        - run:
            name: Setup NPM
            command: echo "//registry.npmjs.org/:_authToken=<<parameters.token>>" >> ~/.npmrc

    deploy-to-npm:
      parameters:
        dir:
          type: string
          default: out
      steps:
        - setup-npm
        - run: npm publish << parameters.dir >>

    setup-git:
      parameters:
        user:
          type: string
          default: Rocky Wu
        email :
          type: string
          default : rwu823@gmail.com
      steps:
        - run:
            name: Setup Git
            command: |
              git config --global user.name '<<parameters.user>>'
              git config --global user.email '<<parameters.email>>'

    push-branch:
      parameters:
        tag:
          type: string
          default: $GIT_TAG
        dir:
          type: string
          default: out
        repo:
          type: string
          default: $TOKEN_REPO
        force:
            type: boolean
            default: false
        branch:
          type: string
          default: $GIT_TAG
      steps:
        - setup-git
        - run:
            name: Push to << parameters.branch >>
            command: |
              cd << parameters.dir >>
              git init
              git add -A
              git commit -nm "<< parameters.tag >>"

              git checkout -b << parameters.branch >>
              git push --quiet <<# parameters.force >> -f <</ parameters.force >> << parameters.repo >> HEAD

              rm -rf .git

    checkout-install:
      description: Checkout sources and install node_modules
      steps:
        - checkout
        - restore_cache:
            key: node_modules#{{ checksum "yarn.lock" }}
        - run: yarn
        - save_cache:
            key: node_modules#{{ checksum "yarn.lock" }}
            paths:
              - node_modules
        - run: git checkout -- .
        - run:
            name: Init Submodule
            command: git submodule update --init --remote --depth 1
        - run:
            name: Decrypt Secret
            command: |
              sudo apt-get -y -qq update
              sudo apt-get install bsdmainutils
              yarn --silent transcrypt -p "$REPO_SECRET" -y
        - run:
            name: Exports Env
            command: |
              echo "$(yarn --silent ts-node scripts/export-env)" >> $BASH_ENV
              echo 'export PATH="$(yarn global bin):$PATH"' >> $BASH_ENV

              source $BASH_ENV

jobs:
  test:
    executor: node
    steps:
      - checkout-install
      - run: npx jest --passWithNoTests
      - run: bash <(curl -s https://codecov.io/bash)
  lint:
    executor: node
    steps:
      - checkout-install
      - run:
          name: Run ESLint only on modified files.
          command: npx eslint $(git diff --diff-filter=d origin/HEAD --name-only --cached '*.ts' '*.tsx' '*.js')

workflows:
  version: 2

  Base:
    jobs:
      - test:
          <<: *branch_testing
      - lint:
          <<: *branch_testing
